#!/bin/sh
echo "Cleaning up after PlutoTV removal..."
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/PlutoTV > /dev/null 2>&1
rm -rf /media/hdd/PlutoTV > /dev/null 2>&1
rm -rf /media/usb/PlutoTV > /dev/null 2>&1
rm -rf /etc/enigma2/PlutoTV > /dev/null 2>&1
exit 0
